from pathlib import Path
p=Path('/home/ubuntu/learnflow-ai/client/src/pages/Home.tsx')
s=p.read_text()
s=s.replace('{section === "Learning Flow" && <LearningFlowView onContinue={() => { selectSection("AI Study"); sendChat("Continue my recursion learning from where I stopped."); }} />}', '{section === "Learning Flow" && <LearningFlowView history={chatHistory} onContinue={() => { selectSection("AI Study"); sendChat("Continue my recursion learning from where I stopped."); }} onOpenQuestion={(question) => { selectSection("AI Study"); sendChat(question); }} />}')
start=s.index('function LearningFlowView({ onContinue }: { onContinue: () => void }) {')
end=s.index('function TeachModeView', start)
new='''function LearningFlowView({ history, onContinue, onOpenQuestion }: { history: ChatHistory[]; onContinue: () => void; onOpenQuestion: (question: string) => void }) {
  const questions = history.flatMap((chat) => chat.messages.filter((message) => message.role === "user").map((message) => ({ question: message.content, chat: chat.title }))).filter((item, index, items) => items.findIndex((candidate) => candidate.question === item.question) === index);
  const flowNodes = questions.length ? questions : [{ question: "Start by asking your first learning question", chat: "New conversation" }];
  return <><SectionLabel eyebrow="MY LEARNING FLOW · QUESTION MAP" title="Your questions become a learning path." note="Every question is saved in history and connected here as a visual flow. Select any node to revisit it." /><div className="flow-layout"><div className="panel flow-main"><div className="flow-main-top"><div className="flow-topic-icon"><Brain size={26} /></div><div><span className="tag violet-tag">PERSONAL QUESTION MAP</span><h2>From curiosity to confident understanding</h2><p>{flowNodes.length} learning nodes · each question is saved in your history</p></div><button className="primary-button" onClick={onContinue}>Continue learning <ChevronRight size={16} /></button></div><div className="timeline flow-question-map">{flowNodes.map((item, index) => <button className={`timeline-row flow-question-node ${index === flowNodes.length - 1 ? "current" : "complete"}`} key={`${item.question}-${index}`} onClick={() => onOpenQuestion(item.question)}><div className="timeline-marker">{index === flowNodes.length - 1 ? <Sparkles size={14} /> : <Check size={14} />}</div><div className="timeline-copy"><span className="eyebrow">NODE {String(index + 1).padStart(2, "0")} · {item.chat}</span><strong>{item.question}</strong><p>Open this question in AI Study and continue the explanation.</p></div><span className="timeline-score"><ArrowUpRight size={14} /></span>{index < flowNodes.length - 1 && <div className="timeline-line" />}</button>)}</div></div><div className="flow-side"><div className="panel confidence-card"><div className="eyebrow">FLOW GUIDE</div><h3>How to use your map</h3><div className="memory-stat"><span>Questions saved</span><strong>{questions.length}</strong><MiniBar value={Math.min(100, questions.length * 20)} tone="mint" /></div><div className="memory-stat"><span>Current node</span><strong>{questions.length ? `Node ${questions.length}` : "Ready"}</strong><MiniBar value={questions.length ? 80 : 10} tone="violet" /></div><div className="memory-callout"><Sparkles size={15} /><span>Tap any node to revisit the exact question and continue learning.</span></div></div><div className="panel weak-card"><div className="eyebrow">FLOW TIP</div><div className="weak-topic"><span>Ask → understand → practice</span><b>Repeat</b></div><div className="weak-topic"><span>Use your history as revision</span><b>Open</b></div></div></div></div></>;
}
'''
s=s[:start]+new+s[end:]
p.write_text(s)
